[versions]
kotlin = "2.2.0"
kotlinx-coroutines = "1.9.0"
kotlinx-serialization = "1.7.3"
shadow = "9.0.0"
hytale-mod = "0.+"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.0.2" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
hytale-mod = { id = "hytale-mod", version.ref = "hytale-mod" }
